version: '3.8'

services:
  orientdb:
    image: orientdb:3.2.0
    ports:
      - "2424:2424"
      - "2480:2480"
    volumes:
      - orientdb_data:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: admin

volumes:
  orientdb_data:
  fake_data:
