services:
  orientdb:
    image: orientdb:3.1.10
    ports:
      - "2424:2424"
      - "2480:2480"
    volumes:
      - orientdb_data:/orientdb/databases
    environment:
      ORIENTDB_ROOT_PASSWORD: admin
  
  loader:
    build: .
    depends_on:
      - orientdb
    volumes:
      - ./data/clean_data:/app/data
      # Remove the Scripts volume mount since we're copying it in Dockerfile
    environment:
      - ORIENTDB_HOST=orientdb
      - ORIENTDB_PORT=2424
      - ORIENTDB_DB=db3
      - ORIENTDB_USER=root
      - ORIENTDB_PASSWORD=admin
    

volumes:
  orientdb_data: